// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohnirddrjmfyuevsvzde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9obmlyZGRyam1meXVldnN2emRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTA1ODgsImV4cCI6MjA2OTI2NjU4OH0.msbrSr-ytP7xvVlfWIPFE6zBtBNIl5nly138MttMPaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});